server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password:  "secret"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration